sudo: false
dist: trusty
cache:
    directories:
        - $HOME/.cache/pip
        - tests/bot-ci
addons:
    apt:
        packages:
            - libssl1.0.0
            - zsh
            - tcsh
            - mksh
            - busybox
            # - rc
            - socat
            - bc
language: python
install: tests/install.sh
script: tests/test.sh
jobs:
    include:
        - stage: PyPy
          python: "pypy"
        - python: "pypy3"
        - stage: Latest Python
          python: "3.6"
        - stage: Intermediate versions
          python: "3.5"
        - python: "3.4"

# vim: et
